### ISSUE TITLE
This branch is 462 commits behind ansible:devel.  -> Still viable?

### ISSUE THREAD

**Issue by BluejacketScott** [bvitnik/ansible#1]
##### SUMMARY

Stale by comparison - should this be updated before use?
##### ISSUE TYPE
- Bug Report
Not really a bug
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

XCP-NG 7.6
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by bvitnik** [comment]
Ansible xenserver_guest module has been merged upstream so you can clone upstream ansible:devel branch to get the latest version. My fork of ansible:devel branch is 462 commits behind upstream because I currently have a number of pull requests for merging two more modules (xenserver_guest_facts and xenserver_guest_powerstate) and some other stuff. These two modules can be found in separate branches. Getting my fork in level with upstream requires me to rebase all my feature branches and pull requests.

If this sounds too confusing, my recommendation is to just clone upstream ansible repo or download an archive at:

https://github.com/ansible/ansible/archive/devel.zip

Then follow the instructions for running Ansible from source found here:

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#running-from-source

At this point you will have access to xenserver_guest module. Please consult the docs here for usage:

https://docs.ansible.com/ansible/devel/modules/xenserver_guest_module.html#xenserver-guest-module
